name: Issue
on:
  schedule:
    # 15:30 UTC = 08:30 America/Los_Angeles (your tz)
    - cron: "30 15 * * *"
  workflow_dispatch:

permissions:
  issues: write
  contents: read

jobs:
  open_issue:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Ensure template exists
        run: test -f .github/ISSUE_TEMPLATE/daily.md

      - name: Open issue if one doesn't exist for today
        uses: actions/github-script@v7
        with:
          script: |
            const {owner, repo} = context.repo;
            const today = new Date().toISOString().slice(0,10);
            const title = `Daily check-in: ${today}`;

            // Search for an existing open issue with today's title
            const search = await github.rest.search.issuesAndPullRequests({
              q: `repo:${owner}/${repo} is:issue is:open in:title "${title}"`
            });
            if (search.data.total_count > 0) {
              core.info('Issue already exists.');
              return;
            }

            // Load the template from the repo
            const fs = require('fs');
            const path = require('path');
            const tmplPath = path.join(process.env.GITHUB_WORKSPACE, '.github/ISSUE_TEMPLATE/daily.md');
            const body = fs.readFileSync(tmplPath, 'utf8')
              .replace('{{date}}', today);

            await github.rest.issues.create({
              owner, repo,
              title,
              body,
              labels: ['daily']
            });
            core.info('Opened new daily check-in issue.');

